global using Examination_System_MVC.Enumeration;
global using Examination_System_MVC.Models;
global using Examination_System_MVC.Repository.InterfaceRepository;
global using Microsoft.EntityFrameworkCore;
global using System.Linq.Expressions;
global using System.Threading.Tasks;
global using System;
global using System.Collections.Generic;
global using Microsoft.EntityFrameworkCore;